server {
    listen 80;
    server_name api-preview.uryuimoveis.com.br;
    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        allow all;
        try_files $uri =404;
    }
    location / { return 404; }
}
